apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Upstream ingress-nginx. Bump version to upgrade.
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.15.1/deploy/static/provider/cloud/deploy.yaml

# Beget: public LB IP.
patches:
  - target:
      kind: Service
      name: ingress-nginx-controller
    patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: ingress-nginx-controller
        annotations:
          lb.beget.com/type: external
